# Send daily emails - time in UTC
name: The Daily Mail
on:
  schedule:
  - cron:  '30 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install environs requests sendgrid
    - name: Send email
      run:  python ./daily_mail.py
      
